DB_HOST: YOUR-DB-HOST
DB_USERNAME: YOUR-DB-USERNAME
DB_PASSWORD: YOUR-DB-PASSWORD

LOGGING_KAFKA_HOST: YOUR-KAFKA-HOST
LOGGING_KAFKA_PORT: YOUR-KAFKA-PORT

REDIS_HOST: YOUR-REDIS-HOST
REDIS_PORT: YOUR-REDIS-PORT
REDIS_PASSWORD: YOUR-REDIS-PASSWORD

logging:
  config: classpath:logback-logstash.xml



