LOGGING_KAFKA_HOST: YOUR-KAFKA-HOST
LOGGING_KAFKA_PORT: YOUR-KAFKA-PORT

SENTINEL_TRANSPORT_PORT: YOUR-SENTINEL-TRANSPORT-PORT
SENTINEL_DASHBORAD_HOST: YOUR-SENTINEL-DASHBORAD-HOST
SENTINEL_DASHBORAD_PORT: YOUR-SENTINEL-DASHBORAD-PORT

logging:
  config: classpath:logback-logstash.xml



